### ISSUE TITLE
Problem posting abbreviated return

### ISSUE THREAD

**Issue by AndyHartley1993** [hmrc/interest-restriction-return#182]
I am currently developing against the Interest Restriction Return API in the sandbox.
On attempting to submit your example abbreviated return, having set the Accept, Content-Type, and Authorization headers in my HttpRequest object to those as specified together with my in-date access-token as a Bearer token.  I receive a 200 OK status code response, BUT the response text comes back as:

   Status 200 Error returned when trying to submit abbreviated return

I don't think I've made a mistake in the protocol, but I am wondering if the endpoint is responding correctly?

The URL for the endpoint I'm calling is:

   https://test-api.service.hmrc.gov.uk/organisations/interest-restriction/return/abbreviated

I would appreciate your advice.

**Comment by AndyHartley1993** [comment]
@DevAndyroo - Any idea why I'm not receiving the expected Json response to the above POST?

**Comment by versatil56** [comment]
Hello Andy,

Thanks for reaching out - we will investigate the issue and get back to you on this.

**Comment by burns238** [comment]
Hi @AndyHartley1993 - thanks for highlighting this issue. This was due to an environmental issue whereby a downstream API was returning an incorrect status code. This is now resolved and sending a valid payload will now result in a success with an acknowledgement reference returned in the body.
