### ISSUE TITLE
Problem posting data to appoint reporting company

### ISSUE THREAD

**Issue by AndyHartley1993** [hmrc/interest-restriction-return#183]
In addition to the error response for submitting an abbreviated return, I thought maybe it might be because I hadn't posted data to the Appoint Reporting Company API.

On attempting to POST the example Json for appointing a reporting company, I receive a 200 OK response code as well as the following response text:

   Status 200 Error returned when trying to appoint a reporting company

I would appreciate your advice.

**Comment by versatil56** [comment]
Hello Andy - Just to acknowledge receipt of your request. We will get back to you once someone looks into it.

**Comment by burns238** [comment]
Hi @AndyHartley1993 - this issue had the same root cause as issue 182 (https://github.com/hmrc/interest-restriction-return/issues/182) which is now resolved meaning that sending a valid payload will now result in a success with an acknowledgement reference returned in the body.
