### ISSUE TITLE
schema validation - definitions

### ISSUE THREAD

**Issue by AndyHartley1993** [hmrc/interest-restriction-return#189]
In the **definitions.json** schema file, why has the **dateType** not got a "pattern" key with a regex value?  Instead it has an "example" key with the value "2020-04-06" which seems a bit pointless.

**Comment by versatil56** [comment]
Hello Andy - Just to acknowledge receipt of your request. We will get back to you once someone looks into it.

**Comment by versatil56** [comment]
Hello Andy - just to confirm that we have added a simplistic regular expression for dates in our schema and will feature in our next deployment. This regular expression focuses on just the `shape` of what constitutes a date for us and not the intricacies of what would be an invalid date even if we meet the regular expression - there will be further validation to cover these cases.

**Comment by AndyHartley1993** [comment]
Would have been better if you had used a regular expression like this:
"((?:19|20)\\d\\d)-(0[1-9]|1[012])-([12][0-9]|3[01]|0[1-9])"
