### ISSUE TITLE
schema validation - subSchemas

### ISSUE THREAD

**Issue by AndyHartley1993** [hmrc/interest-restriction-return#190]
All of the schema files in the subSchemas folder have a root level **description** key with associated description in the value element.  This is very helpful when reporting back when a validation error is found to help identify the location of the error.  However the following schemas in the subSchemas folder don't have such a key value pair:

- agentDetails.json
- allocatedReactivations.json
- allocatedRestrictions.json

Can you please add such a key value pair for the description key to these three schema files?

**Comment by versatil56** [comment]
Hello Andy - Just to acknowledge receipt of your request. We will get back to you once someone looks into it.

**Comment by burns238** [comment]
Hi Andy, descriptions have been added to each of these subschemas now alongside general updates to the schema descriptions.
