### ISSUE TITLE
schema validations - country codes

### ISSUE THREAD

**Issue by AndyHartley1993** [hmrc/interest-restriction-return#192]
Are you planning on adding a list of ISO 3166-1 2-digit country codes to the countrycodes.json in the definitions folder?

**Comment by versatil56** [comment]
Hello Andy - Just to acknowledge receipt of your request. We will get back to you once someone looks into it.

**Comment by burns238** [comment]
Hi @AndyHartley1993, the list of valid country codes can be found in app/config/Constants.scala. The schema in our application is used primarily to populate the documentation in the HMRC Developer Hub (https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/interest-restriction-return/1.0) and does not cover all validation for our API. 

Our intention is to create a service guide in the future which is where we will keep an up to date list of the valid country codes alongside other validation rules, but for now they're available in the above file in this repo.
