### ISSUE TITLE
OAuth2 - problem with your web page to get authorisation code

### ISSUE THREAD

**Issue by AndyHartley1993** [hmrc/interest-restriction-return#198]
Yesterday evening I thought I would try out the IRR process from getting authorisation code, exchange that for access token and send Json for appointing company.  I used the supplied credentials and logged in, and then received the following:

![image](https://user-images.githubusercontent.com/74418458/114149841-41a9af80-9913-11eb-82a3-02e1eb18f120.png)

I have this morning tried again, and I still get the same.  Can you please look into this?  The last time I attempted this about a month ago it was working up to the point of receiving the response to the Json submission, as you are aware and have now fixed.

**Comment by AndyHartley1993** [comment]
I am still encountering this issue.  Can someone please investigate?
@burns238

**Comment by versatil56** [comment]
Hello Andy,

This looks like an issue with our platform, rather than the actual `interest-restrictions-return` API . To be certain of this, would you be able to supply a list of steps so that we can attempt to replicate the issue you are experiencing and we can rule out an issue with `interest-restriction-return` API.

As a heads up, if this is not an issue with the `interest-restriction-return` API then I would suggest you try and reach support through this link:

https://developer.service.hmrc.gov.uk/developer/support

Thanks

**Comment by AndyHartley1993** [comment]
Hi Juan,

Thanks for the reply.  I'm initially following the steps here to get the initial access token
https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints 
Just after the sign in stage:
![image](https://user-images.githubusercontent.com/74418458/114730345-b0827080-9d38-11eb-8cf2-27a7502dc4f3.png)

I then get the "Sorry, we're experiencing technical difficulties" page instead of the authorise our application for IRR etc...

**Comment by versatil56** [comment]
Thanks Andy,

This looks like it sits outside the action range of our API, `interest-restriction-return`. I would encourage you to submit a support request through the link I sent above.

I will leave this opened - then we can track it. Please let me know if you get nowhere with your support ticket.

**Comment by AndyHartley1993** [comment]
Will do.

**Comment by AndyHartley1993** [comment]
Hi,
I have received a couple of emails in reply to the issue I encountered.  In the last email HMRC online support said that the OAuth2 process is working as they "successfully ran a test".  I then generated some fresh sandbox credentials and the OAuth2 process then worked for me.  This I find is a bit odd and I have advised as such.  I don't know why my original sandbox credentials started resulting in the "technical difficulties" response, but at least I have it working again.

**Comment by versatil56** [comment]
Hi Andy,

Many thanks for letting me know and getting back to me, it is very strange but I'm glad you got it working again. Are you happy for me to close this or should we leave it open for a few days in case it reoccurrs?

**Comment by AndyHartley1993** [comment]
Yes, maybe leave this open for now.  Thanks.

**Comment by AndyHartley1993** [comment]
You can probably close this now.  I don't think anyone is going to investigate why such an odd message started coming back for my previous sandbox credentials!

**Comment by versatil56** [comment]
Ok Andy - thanks for this. Any problems, get back to us.
