### ISSUE TITLE
Posting HMRC example 'Submit a full IRR' - returns 400 error

### ISSUE THREAD

**Issue by AndyHartley1993** [hmrc/interest-restriction-return#251]
I have just tried submitting your example for a full IRR from:

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/interest-restriction-return/1.0#return-submission_post-a-full-interest-restriction-return_post_accordion

I get a 400 response with the following reason:

[{"field":"/returnContainsEstimates","value":true,"errors":["An estimate needs to be supplied in groupEstimateReason or companyEstimateReason where returnContainsEstimates is set to true"]}]

Can you please update this example so we receive a successful submission response please?  Maybe use the current example as an example of an error scenario.

**Comment by AndyHartley1993** [comment]
I changed returnContainsEstimates to true, and this then results in a successful submission response.

**Comment by versatil56** [comment]
Hello Andy - thanks for this. We will be in touch shortly.

**Comment by versatil56** [comment]
Hello Andy - just to let you know that this is fixed and will feature in our next deployment. I'm going to leave this open then I can let you know when we have deployed, at the latest tomorrow.
