### ISSUE TITLE
question about the subSchemer AllocatedRestrictions.json

### ISSUE THREAD

**Issue by JonathanTucker** [hmrc/interest-restriction-return#254]
Good morning 
I have a question about the AllocatedRestriction.json and why it's been set up to only record up to 3 company periods in the group period along with their disallowed amounts?

What are companies with more than 3 periods supposed to do in this scenario?
could this be updated to be a repeatable item so that all periods in a company can be recorded no matter how many periods they have?

**Comment by versatil56** [comment]
Hello Jonathan, 

Just to let you know that we have received your query and will be back in touch shortly with a suitable answer.

Many Thanks.

**Comment by burns238** [comment]
Hi @JonathanTucker,

Thanks for the query. Updating this to allow for more than 3 accounting periods is out of scope for this project and is seen as a highly unlikely scenario by the business. My understanding is that you have contacted our platform team who have responded about this request so I'm going to close this issue.

Cheers,

Mike
