### ISSUE TITLE
Json response when an error occurs

### ISSUE THREAD

**Issue by AndyHartley1993** [hmrc/interest-restriction-return#269]
The web page at:
https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#errors
states that the Json returned when an error or multiple errors have been found in a submission will be structured like this:
![image](https://user-images.githubusercontent.com/74418458/118647352-29159a80-b7d9-11eb-97d0-12b389848d54.png)

but I have just received an error response as follows:
![image](https://user-images.githubusercontent.com/74418458/118647509-52362b00-b7d9-11eb-8319-f918bd2ddf2e.png)

This is not the expected format.  I await your advice on the matter.

**Comment by AndyHartley1993** [comment]
This is another error response I have received:
![image](https://user-images.githubusercontent.com/74418458/118671856-b9f77080-b7ef-11eb-9748-a6bda2ed37a6.png)
Again, this does not conform to the Json structure set out in the above web page I gave the URL to.  It is all enclosed in square brackets and not braces, and the structure of { "code": "...", "message": "...", "errors": [ ... ] }

**Comment by burns238** [comment]
Hi @AndyHartley1993,

Thanks for raising this issue. We are currently refactoring our error handling such that errors will be returned in the format documented above, following the HMRC standards. This is currently being tested and I'll let you know via this issue when it's been deployed to the sandbox environment.

Cheers,

Mike

**Comment by AndyHartley1993** [comment]
@burns238 - Mike, have your code changes for returning the Json when an error(s) occurs been fully tested yet?  If so, have they been deployed to the sandbox?

**Comment by versatil56** [comment]
Andy - this was pushed yesterday to sandbox. 

Cheers
