### ISSUE TITLE
List of all possible 400-499 errors

### ISSUE THREAD

**Issue by JonathanTucker** [hmrc/interest-restriction-return#274]
Good morning

I was wondering if it was possible to get a list of all possible errors that can arise when submitting one of the corporate interest restrictions APIs.
I have looked on the API documentation page and can see the error codes between 400 and 499 related to client error etc but I cannot see a list of what errors you actually check for. (and I have looked in https://github.com/hmrc/interest-restriction-return/tree/master/public/api/)

For example, I am looking for errors like
"errors": ["You need to appoint a reporting company"]
 "errors": ["you have given details for a UK Partnership and NonUK Company"]
(and if possible what actually triggers them to display)
This would be useful so that we can warn users if their submission is going to fail or not before they submit their returns.

**Comment by versatil56** [comment]
Hello Jonathan, we are planning on the release of a Service Guide that will feature all errors.

We will be in touch when this Service Guide is released.

Many Thanks.
