### ISSUE TITLE
groupRatio adjustedGroupInterest when blended election is in use

### ISSUE THREAD

**Issue by JonathanTucker** [hmrc/interest-restriction-return#316]
Hi 
I have a quick question on how you want the API to be populated when the group ratio blended election is used.
Looking at the schemer files I can see the groupRatio" element and how this is calculated 
 I.E - the scheme say its "QNGIE divided by the group-EBITDA",

So if had a particular scenario where QNGIE was £15,080,000 and group-EBITDA was £45,060,000 then the group ratio would be 33.46649 (rounded to 5dp as per the schemer.
Which we then multiple by the aggregate tax-EBITDA to be used in the rest of the calculation.

However if the group ratio blended election is in use then we use the blended result as calculated in TIOPA 2010 s401 which can give you a very different result based on the investor numbers lets say the end result is a blended % of 48%

Should I be putting the blended group ratio result in the groupRatio element here or still use the above figure of 33.46649? given that the Aggregate tax-EBITDA will be multiplied by the 48%

**Comment by burns238** [comment]
Hi @JonathanTucker,

Thanks for the query. I've raised this with the team and I will update you here once I have an answer.

Cheers,

Mike

**Comment by burns238** [comment]
Hi @JonathanTucker,

Thanks for raising this. We're implementing a fix to ensure that the Group Ratio Blended result can be used in the groupRatio field. The fix involves removing this piece of validation for the groupRatio field and the understanding is that the user will be submitting a valid value. 

This will be available in the sandbox environment from later today.

Thanks,

Mike
