### ISSUE TITLE
Validation endpoint - odd status code being returned

### ISSUE THREAD

**Issue by AndyHartley1993** [hmrc/interest-restriction-return#326]
I am currently implementing use of the validation endpoints for the IIR as per:

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/interest-restriction-return/1.0#Validate%20a%20Full%20Interest%20Restriction%20Return

I am sending a small test json file that when sent to the following API receives a successful submission acknowledgment reference:

https://test-api.service.hmrc.gov.uk/organisations/interest-restriction/return/full

but when I send to the /validate endpoint, as follows:

https://test-api.service.hmrc.gov.uk/organisations/interest-restriction/return/full/validate

instead of the expected 204 status code response, I'm receiving a status code of: **1223**.  I find this rather strange.  What are your comments on this?

**Comment by anburoach** [comment]
Hello Andy, IRR is returning 204 it may be an issue with the application which you are using.  Could you please let us know how did you test this? And please try the same request in curl.

**Comment by AndyHartley1993** [comment]
Hi, I'm using my code in our software.  Using the same code to send data to the /appoint, /revoke, /full and /abbreviated endpoints all work as expected.  It is only when I send a test submission with valid json payload to either of the following endpoints:

https://test-api.service.hmrc.gov.uk/organisations/interest-restriction/return/abbreviated/validate

or

https://test-api.service.hmrc.gov.uk/organisations/interest-restriction/return/full/validate

when reading the returned status code that I receive a 1223 and not a 204 that is expected with a valid payload.

If I send json payload with an invalid UTR, I receive the expected result back.

**Comment by AndyHartley1993** [comment]
If I send the same data with same bearer token etc, using Postman I receive a 204 response.
It's really odd, as my same code for a POST with all the other API endpoints is working fine, and I even get the expected response when I send an invalid Json payload.  Only when I send a valid Json payload expecting a 204 response do I receive a response code of 1223, and the HRESULT from the XMLHTTPRequest send(...)

**Comment by AndyHartley1993** [comment]
It would appear that the XMLHTTPRequest object (which is what I'm using) is not interpreting the 204 status code and is generating a status code of 1223, see:
https://stackoverflow.com/questions/10046972/msie-returns-status-code-of-1223-for-ajax-request

**Comment by Blaine-k** [comment]
Hi @AndyHartley1993, the best way to get further assistance with your issue will be to contact the Software Developer Support Team. You can do this either by emailing them at **sdsteam@hmrc.gov.uk**, or by raising a ticket via your Developer Hub account.

Please do the same for any future issues or queries relating to IRR. Thank you!

**Comment by AndyHartley1993** [comment]
@Blaine-k  thank you but I resolved the issue via my code.  I was just letting the team here know.
